const farmerProducts = [

  // ✅ सरदारशहर
  {
  id: 1,
  productName: "बोरिया",
  cropType: "स्थानीय उत्पाद",
  farmerName: "रामकिशन विश्नोई",
  district: "चूरू",
  subDistrict: "तारानगर",
  location: "तारानगर, चूरू",
  price: 150,
  quantity: "25 पीस",
  image: "/Images/boriya.png",
  contact: "9876001111",
  description:
    "ऊंट या बकरी के बाल से बनी पारंपरिक बोरिया, ग्रामीण क्षेत्रों में उपयोगी।",
},
{
  id: 2,
  productName: "देशी घी",
  cropType: "दुग्ध उत्पाद",
  farmerName: "मोहनलाल",
  district: "चूरू",
  subDistrict: "सुजानगढ़",
  location: "सुजानगढ़, चूरू",
  price: 950,
  quantity: "1 किलो",
  image: "/Images/ghee.png",
  contact: "9876001113",
  description:
    "शुद्ध देसी गाय के दूध से बना पारंपरिक घी।",
},
  {
    id: 3,
    productName: "सरसों",
    cropType: "सरसों",
    farmerName: "बाबूलाल जाट",
    district: "चूरू",
    subDistrict: "सरदारशहर",
    location: "सरदारशहर, चूरू",
    price: 5700,
    quantity: "7 क्विंटल",
    image: "/Images/mustard.png",
    contact: "9876500002",
    description: "उच्च तेल गुणवत्ता वाली सरसों।",
  },
  

{
  id: 32,
  productName: "काचरा",
  cropType: "स्थानीय उत्पाद",
  farmerName: "हनुमानराम जाट",
  district: "चूरू",
  subDistrict: "सरदारशहर",
  location: "सरदारशहर, चूरू",
  price: 1200,
  quantity: "10 किलो",
  image: "/Images/kachara.png",
  contact: "9876001112",
  description:
    "राजस्थान की पारंपरिक सूखी सब्जी काचरा, अचार और सब्जी बनाने में उपयोगी।",
},



  {
    id: 4,
    productName: "मूंग",
    cropType: "मूंग",
    farmerName: "शिवनारायण",
    district: "चूरू",
    subDistrict: "चूरू",
    location: "चूरू, चूरू",
    price: 7200,
    quantity: "5 क्विंटल",
    image: "/Images/moong.png",
    contact: "9876500003",
    description: "ताज़ी और साफ मूंग।",
  },
  {
    id: 5,
    productName: "बाजरा",
    cropType: "बाजरा",
    farmerName: "मंगतराम",
    district: "चूरू",
    subDistrict: "सरदारशहर",
    location: "सरदारशहर, चूरू",
    price: 2300,
    quantity: "12 क्विंटल",
    image: "/Images/bajara.png",
    contact: "9876500004",
    description: "सूखे क्षेत्र का पौष्टिक बाजरा।",
  },
  

  // ✅ रतनगढ़
  {
    id: 6,
    productName: "सरसों",
    cropType: "सरसों",
    farmerName: "मोहन सिंह",
    district: "चूरू",
    subDistrict: "रतनगढ़",
    location: "रतनगढ़, चूरू",
    price: 5600,
    quantity: "8 क्विंटल",
    image: "/Images/mustard.png",
    contact: "9998887770",
    description: "उच्च गुणवत्ता वाली सरसों।",
  },
  {
    id: 7,
    productName: "गेहूँ",
    cropType: "गेहूँ",
    farmerName: "गंगाराम",
    district: "चूरू",
    subDistrict: "रतनगढ़",
    location: "रतनगढ़, चूरू",
    price: 2350,
    quantity: "14 क्विंटल",
    image: "/Images/wheat.png",
    contact: "9998887701",
    description: "ताज़ा और साफ गेहूँ।",
  },
  {
    id: 9,
    productName: "चना",
    cropType: "चना",
    farmerName: "ओमप्रकाश",
    district: "चूरू",
    subDistrict: "रतनगढ़",
    location: "रतनगढ़, चूरू",
    price: 5150,
    quantity: "6 क्विंटल",
    image: "/Images/chana.png",
    contact: "9998887703",
    description: "पोषक तत्वों से भरपूर चना।",
  },
  {
  id: 34,
  productName: "गोबर के उपले",
  cropType: "स्थानीय उत्पाद",
  farmerName: "गीता देवी",
  district: "चूरू",
  subDistrict: "राजगढ़",
  location: "राजगढ़, चूरू",
  price: 200,
  quantity: "50 पीस",
  image: "/Images/upale.png",
  contact: "9876001114",
  description:
    "पूजा और ईंधन के लिए उपयोग होने वाले पारंपरिक गोबर के उपले।",
},

{
  id: 35,
  productName: "ऊंट का दूध",
  cropType: "दुग्ध उत्पाद",
  farmerName: "सलीम खान",
  district: "चूरू",
  subDistrict: "रतनगढ़",
  location: "रतनगढ़, चूरू",
  price: 120,
  quantity: "1 लीटर",
  image: "/Images/milk.png",
  contact: "9876001115",
  description:
    "ऊंट का ताज़ा दूध, स्वास्थ्य के लिए लाभदायक।",
},
  {
    id: 10,
    productName: "मूंगफली",
    cropType: "मूंगफली",
    farmerName: "शंकरलाल",
    district: "चूरू",
    subDistrict: "रतनगढ़",
    location: "रतनगढ़, चूरू",
    price: 5800,
    quantity: "5 क्विंटल",
    image: "/Images/groundnut.png",
    contact: "9998887704",
    description: "तेल उत्पादन के लिए उत्तम मूंगफली।",
  },

  // ✅ तारानगर
  {
    id: 11,
    productName: "बाजरा",
    cropType: "बाजरा",
    farmerName: "धर्मपाल",
    district: "चूरू",
    subDistrict: "तारानगर",
    location: "तारानगर, चूरू",
    price: 2250,
    quantity: "10 क्विंटल",
    image: "/Images/bajara.png",
    contact: "9988776601",
    description: "उत्तम गुणवत्ता बाजरा।",
  },
  {
    id: 12,
    productName: "ग्वार",
    cropType: "ग्वार",
    farmerName: "महावीर",
    district: "चूरू",
    subDistrict: "तारानगर",
    location: "तारानगर, चूरू",
    price: 5200,
    quantity: "7 क्विंटल",
    image: "/Images/guar.png",
    contact: "9988776602",
    description: "ग्वार गम उद्योग के लिए उपयोगी।",
  },
  {
    id: 13,
    productName: "सरसों",
    cropType: "सरसों",
    farmerName: "रामनिवास",
    district: "चूरू",
    subDistrict: "तारानगर",
    location: "तारानगर, चूरू",
    price: 5650,
    quantity: "6 क्विंटल",
    image: "/Images/mustard.png",
    contact: "9988776603",
    description: "तेल गुणवत्ता वाली सरसों।",
  },
  {
    id: 14,
    productName: "चना",
    cropType: "चना",
    farmerName: "किशनलाल",
    district: "चूरू",
    subDistrict: "तारानगर",
    location: "तारानगर, चूरू",
    price: 5200,
    quantity: "9 क्विंटल",
    image: "/Images/chana.png",
    contact: "9988776604",
    description: "स्वच्छ और अच्छी गुणवत्ता चना।",
  },
 
  // ✅ सुजानगढ़
  {
    id: 16,
    productName: "मूंग",
    cropType: "मूंग",
    farmerName: "जगदीश",
    district: "चूरू",
    subDistrict: "सुजानगढ़",
    location: "सुजानगढ़, चूरू",
    price: 7100,
    quantity: "5 क्विंटल",
    image: "/Images/moong.png",
    contact: "9977665501",
    description: "ताज़ी मूंग।",
  },
  {
    id: 17,
    productName: "तिल",
    cropType: "तिल",
    farmerName: "घनश्याम",
    district: "चूरू",
    subDistrict: "सुजानगढ़",
    location: "सुजानगढ़, चूरू",
    price: 8200,
    quantity: "4 क्विंटल",
    image: "/Images/sesame.png",
    contact: "9977665502",
    description: "तेल उत्पादन के लिए उच्च गुणवत्ता तिल।",
  },
  
  {
    id: 19,
    productName: "चना",
    cropType: "चना",
    farmerName: "प्रहलाद",
    district: "चूरू",
    subDistrict: "सुजानगढ़",
    location: "सुजानगढ़, चूरू",
    price: 5300,
    quantity: "6 क्विंटल",
    image: "/Images/chana.png",
    contact: "9977665504",
    description: "पोषणयुक्त चना।",
  },
  {
    id: 20,
    productName: "बाजरा",
    cropType: "बाजरा",
    farmerName: "नारायण",
    district: "चूरू",
    subDistrict: "सुजानगढ़",
    location: "सुजानगढ़, चूरू",
    price: 2300,
    quantity: "10 क्विंटल",
    image: "/Images/bajara.png",
    contact: "9977665505",
    description: "गर्मी सहनशील बाजरा।",
  },

  // ✅ राजगढ़
  {
    id: 21,
    productName: "गेहूँ",
    cropType: "गेहूँ",
    farmerName: "विजय सिंह",
    district: "चूरू",
    subDistrict: "राजगढ़",
    location: "राजगढ़, चूरू",
    price: 2420,
    quantity: "12 क्विंटल",
    image: "/Images/wheat.png",
    contact: "9966554401",
    description: "उच्च गुणवत्ता गेहूँ।",
  },
  {
    id: 22,
    productName: "सरसों",
    cropType: "सरसों",
    farmerName: "हरीश",
    district: "चूरू",
    subDistrict: "राजगढ़",
    location: "राजगढ़, चूरू",
    price: 5600,
    quantity: "7 क्विंटल",
    image: "/Images/mustard.png",
    contact: "9966554402",
    description: "तेल युक्त सरसों।",
  },
  {
    id: 23,
    productName: "चना",
    cropType: "चना",
    farmerName: "रामकुमार",
    district: "चूरू",
    subDistrict: "राजगढ़",
    location: "राजगढ़, चूरू",
    price: 5250,
    quantity: "6 क्विंटल",
    image: "/Images/chana.png",
    contact: "9966554403",
    description: "स्वच्छ चना।",
  },
  {
    id: 24,
    productName: "ग्वार",
    cropType: "ग्वार",
    farmerName: "जगताराम",
    district: "चूरू",
    subDistrict: "राजगढ़",
    location: "राजगढ़, चूरू",
    price: 5100,
    quantity: "8 क्विंटल",
    image: "/Images/guar.png",
    contact: "9966554404",
    description: "ग्वार गम उद्योग के लिए।",
  },
  {
    id: 25,
    productName: "मूंगफली",
    cropType: "मूंगफली",
    farmerName: "सुरेश",
    district: "चूरू",
    subDistrict: "राजगढ़",
    location: "राजगढ़, चूरू",
    price: 5750,
    quantity: "5 क्विंटल",
    image: "/Images/groundnut.png",
    contact: "9966554405",
    description: "तेल उत्पादन के लिए उत्तम।",
  },

  // ✅ चूरू शहर
  {
    id: 26,
    productName: "मक्का",
    cropType: "मक्का",
    farmerName: "सतीश",
    district: "चूरू",
    subDistrict: "चूरू शहर",
    location: "चूरू शहर",
    price: 2100,
    quantity: "7 क्विंटल",
    image: "/Images/corn.png",
    contact: "9955443301",
    description: "बेहतरीन मक्का।",
  },
  {
    id: 27,
    productName: "गेहूँ",
    cropType: "गेहूँ",
    farmerName: "अशोक",
    district: "चूरू",
    subDistrict: "चूरू शहर",
    location: "चूरू शहर",
    price: 2390,
    quantity: "11 क्विंटल",
    image: "/Images/wheat.png",
    contact: "9955443302",
    description: "उच्च गुणवत्ता गेहूँ।",
  },
  {
    id: 28,
    productName: "सरसों",
    cropType: "सरसों",
    farmerName: "राजेश",
    district: "चूरू",
    subDistrict: "चूरू शहर",
    location: "चूरू शहर",
    price: 5650,
    quantity: "6 क्विंटल",
    image: "/Images/mustard.png",
    contact: "9955443303",
    description: "तेल गुणवत्ता वाली सरसों।",
  },
  {
    id: 29,
    productName: "चना",
    cropType: "चना",
    farmerName: "दीपक",
    district: "चूरू",
    subDistrict: "चूरू शहर",
    location: "चूरू शहर",
    price: 5200,
    quantity: "5 क्विंटल",
    image: "/Images/chana.png",
    contact: "9955443304",
    description: "पोषक तत्वों से भरपूर चना।",
  },
  {
    id: 30,
    productName: "बाजरा",
    cropType: "बाजरा",
    farmerName: "महेंद्र",
    district: "चूरू",
    subDistrict: "चूरू शहर",
    location: "चूरू शहर",
    price: 2250,
    quantity: "9 क्विंटल",
    image: "/Images/bajara.png",
    contact: "9955443305",
    description: "पौष्टिक बाजरा।",
  },
];

export default farmerProducts;
